[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#00D4FF"
backgroundColor = "#0A0A0A"
secondaryBackgroundColor = "#1A1A2E"
textColor = "#FFFFFF"
